FS_PATH_PROP = 'fs_path'
OUT_FOLDER_PROP = 'out_folder'
LEVEL_PATH_PROP = 'level_path'
SETTINGS_FILE_NAME = 'stalker_resource_copier.ini'
GITHUB_REPO_URL = 'https://github.com/PavelBlend/stalker-resource-copier'
